asd

diff --git a/.github/workflows/local-test.yml b/.github/workflows/local-test.yml
--- a/.github/workflows/local-test.yml
+++ b/.github/workflows/local-test.yml
@@ -1,7 +1,3 @@
-# https://github.com/actions-rs/grcov
-
-# https://github.com/actions-rs/cargo
-
 name: Local Tests
 
 on:
@@ -34,6 +30,7 @@ jobs:
         run: |
           curl -LsSf https://get.nexte.st/latest/linux | tar zxf - -C ${CARGO_HOME:-~/.cargo}/bin
 
+      # Note - doing this with `cargo install grcov` also works, but is a bit slower
       - name: Install grcov
         id: install_grcov
         run: |
@@ -55,6 +52,7 @@ jobs:
 
       # - name: Unit Test Codecov
       #   id: codedov
+      #   needs: run_grcov
       #   uses: codecov/codecov-action@v3
       #   with:
       #     files: ./lcov.info
@@ -70,17 +68,21 @@ jobs:
         uses: actions/checkout@v3
 
       # use the public name of the action
-      - name: redoc-cli test
+      - name: Redoc
+        id: run_redoc
         uses: seeebiii/redoc-cli-github-action@v10
         with:
-          args: "bundle -o ./open-api-docs.html ./docs/rpc/openapi.yaml"
+          args: "bundle -o /dist/open-api-docs.html ./docs/rpc/openapi.yaml"
 
       - name: check result
+        id: check_redoc
         run: |
-          ls -al
-          test -f ./open-api-docs.html || (echo "Missing ./open-api-docs.html from previous step." && exit 1)
+          test -f /dist/open-api-docs.html || (echo "Missing ./open-api-docs.html from previous step." && exit 1)
 
-      # - uses: codecov/codecov-action@v1
-      #   with:
-      #     token: ${{ secrets.CODECOV_TOKEN }}
-      #     file: ./lcov.info
+      - name: Upload bundled html
+        id: upload_html_artifact
+        uses: actions/upload-artifact@v3
+        with:
+          name: open-api-bundle
+          path: |
+            dist
